/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  documentation: [
    'intro',
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/authentication',
        'api/contract',
        'api/endpoints/index',
        {
          type: 'category',
          label: 'Məhsul kataloqu',
          collapsible: true,
          collapsed: false,
          items: [
            {type: 'doc', id: 'api/modules/products/index', label: 'İcmal'},
            {
              type: 'category',
              label: 'Məhsullar',
              collapsible: true,
              collapsed: true,
              items: [
                {type: 'doc', id: 'api/modules/products/catalog-products', label: 'İcmal'},
                {type: 'doc', id: 'api/modules/products/products/list', label: 'Məhsulları siyahıla'},
                {type: 'doc', id: 'api/modules/products/products/create', label: 'Məhsul yarat'},
                {type: 'doc', id: 'api/modules/products/products/get', label: 'Məhsulu oxu'},
                {type: 'doc', id: 'api/modules/products/products/replace', label: 'Məhsulu tam yenilə'},
                {type: 'doc', id: 'api/modules/products/products/update', label: 'Məhsulu qismən yenilə'},
                {type: 'doc', id: 'api/modules/products/products/delete', label: 'Məhsulu sil'},
                {type: 'doc', id: 'api/modules/products/products/save-branch-settings', label: 'Filial sazlamasını yaz'},
                {type: 'doc', id: 'api/modules/products/products/delete-branch-settings', label: 'Filial sazlamasını sil'},
              ],
            },
            {type: 'doc', id: 'api/modules/products/product-templates', label: 'Məhsul şablonları'},
            {type: 'doc', id: 'api/modules/products/categories', label: 'Kateqoriyalar'},
            {type: 'doc', id: 'api/modules/products/units', label: 'Ölçü vahidləri'},
            {type: 'doc', id: 'api/modules/products/product-packagings', label: 'Qablaşdırmalar'},
            {type: 'doc', id: 'api/modules/products/product-attributes', label: 'Atributlar'},
          ],
        },
        {
          type: 'category',
          label: 'Satış',
          collapsible: true,
          collapsed: true,
          items: [
            {type: 'doc', id: 'api/modules/sales/index', label: 'İcmal'},
            {
              type: 'category', label: 'Satış sifarişləri', collapsible: true, collapsed: true,
              items: [
                {type: 'doc', id: 'api/modules/sales/sale-orders', label: 'İcmal'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/list', label: 'Sifarişləri siyahıla'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/create', label: 'Sifariş yarat'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/get', label: 'Sifarişi oxu'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/replace', label: 'Sifarişi tam yenilə'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/update', label: 'Sifarişi qismən yenilə'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/delete', label: 'Sifarişi sil'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/change-state', label: 'Sifarişin vəziyyətini dəyiş'},
              ],
            },
            {
              type: 'category', label: 'Satış qəbzləri', collapsible: true, collapsed: true,
              items: [
                {type: 'doc', id: 'api/modules/sales/sale-receipts', label: 'İcmal'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/list', label: 'Qəbzləri siyahıla'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/create', label: 'Qəbz yarat'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/get', label: 'Qəbzi oxu'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/replace', label: 'Qəbzi tam yenilə'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/update', label: 'Qəbzi qismən yenilə'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/delete', label: 'Qəbzi sil'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/change-state', label: 'Qəbzin vəziyyətini dəyiş'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Satınalma',
          collapsible: true,
          collapsed: true,
          items: [
            {type: 'doc', id: 'api/modules/purchase/index', label: 'İcmal'},
            {
              type: 'category', label: 'Alış sifarişləri', collapsible: true, collapsed: true,
              items: [
                {type: 'doc', id: 'api/modules/purchase/purchase-orders', label: 'İcmal'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/list', label: 'Sifarişləri siyahıla'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/create', label: 'Sifariş yarat'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/get', label: 'Sifarişi oxu'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/replace', label: 'Sifarişi tam yenilə'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/update', label: 'Sifarişi qismən yenilə'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/delete', label: 'Sifarişi sil'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/change-state', label: 'Sifarişin vəziyyətini dəyiş'},
              ],
            },
            {
              type: 'category', label: 'Alış qəbzləri', collapsible: true, collapsed: true,
              items: [
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts', label: 'İcmal'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/list', label: 'Qəbzləri siyahıla'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/create', label: 'Qəbz yarat'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/get', label: 'Qəbzi oxu'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/replace', label: 'Qəbzi tam yenilə'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/update', label: 'Qəbzi qismən yenilə'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/delete', label: 'Qəbzi sil'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/change-state', label: 'Qəbzin vəziyyətini dəyiş'},
              ],
            },
          ],
        },
        'api/coverage',
      ],
    },
    {
      type: 'category',
      label: 'Arxitektura',
      items: [
        'architecture/overview',
        'architecture/request-lifecycle',
        'architecture/tenancy',
        'architecture/resources',
        'architecture/business-documents',
      ],
    },
    'modules/index',
    'contributing',
  ],
};
