/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  documentation: [
    'intro',
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/authentication',
        'api/contract',
        'api/endpoints/index',
        {
          type: 'category',
          label: 'Məhsul kataloqu',
          collapsible: true,
          collapsed: false,
          items: [
            {type: 'doc', id: 'api/modules/products/index', label: 'İcmal'},
            {
              type: 'category',
              label: 'Məhsullar',
              collapsible: true,
              collapsed: true,
              items: [
                {type: 'doc', id: 'api/modules/products/catalog-products', label: 'İcmal'},
                {type: 'doc', id: 'api/modules/products/products/list', label: 'GET Məhsulları siyahıla'},
                {type: 'doc', id: 'api/modules/products/products/create', label: 'POST Məhsul yarat'},
                {type: 'doc', id: 'api/modules/products/products/get', label: 'GET Məhsulu oxu'},
                {type: 'doc', id: 'api/modules/products/products/replace', label: 'PUT Məhsulu yenilə'},
                {type: 'doc', id: 'api/modules/products/products/update', label: 'PATCH Məhsulu yenilə'},
                {type: 'doc', id: 'api/modules/products/products/delete', label: 'DELETE Məhsulu sil'},
                {type: 'doc', id: 'api/modules/products/products/save-branch-settings', label: 'PUT Filial sazlamasını yaz'},
                {type: 'doc', id: 'api/modules/products/products/delete-branch-settings', label: 'DELETE Filial sazlamasını sil'},
              ],
            },
            {type: 'doc', id: 'api/modules/products/product-templates', label: 'Məhsul şablonları'},
            {type: 'doc', id: 'api/modules/products/categories', label: 'Kateqoriyalar'},
            {type: 'doc', id: 'api/modules/products/units', label: 'Ölçü vahidləri'},
            {type: 'doc', id: 'api/modules/products/product-packagings', label: 'Qablaşdırmalar'},
            {type: 'doc', id: 'api/modules/products/product-attributes', label: 'Atributlar'},
          ],
        },
        {
          type: 'category',
          label: 'Satış',
          collapsible: true,
          collapsed: true,
          items: [
            {type: 'doc', id: 'api/modules/sales/index', label: 'İcmal'},
            {
              type: 'category', label: 'Satış sifarişləri', collapsible: true, collapsed: true,
              items: [
                {type: 'doc', id: 'api/modules/sales/sale-orders', label: 'İcmal'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/list', label: 'GET Sifarişləri siyahıla'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/create', label: 'POST Sifariş yarat'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/get', label: 'GET Sifarişi oxu'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/replace', label: 'PUT Sifarişi yenilə'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/update', label: 'PATCH Sifarişi yenilə'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/delete', label: 'DELETE Sifarişi sil'},
                {type: 'doc', id: 'api/modules/sales/sale-orders/change-state', label: 'PATCH Sifariş state-i'},
              ],
            },
            {
              type: 'category', label: 'Satış qəbzləri', collapsible: true, collapsed: true,
              items: [
                {type: 'doc', id: 'api/modules/sales/sale-receipts', label: 'İcmal'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/list', label: 'GET Qəbzləri siyahıla'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/create', label: 'POST Qəbz yarat'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/get', label: 'GET Qəbzi oxu'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/replace', label: 'PUT Qəbzi yenilə'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/update', label: 'PATCH Qəbzi yenilə'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/delete', label: 'DELETE Qəbzi sil'},
                {type: 'doc', id: 'api/modules/sales/sale-receipts/change-state', label: 'PATCH Qəbz state-i'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Satınalma',
          collapsible: true,
          collapsed: true,
          items: [
            {type: 'doc', id: 'api/modules/purchase/index', label: 'İcmal'},
            {
              type: 'category', label: 'Alış sifarişləri', collapsible: true, collapsed: true,
              items: [
                {type: 'doc', id: 'api/modules/purchase/purchase-orders', label: 'İcmal'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/list', label: 'GET Sifarişləri siyahıla'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/create', label: 'POST Sifariş yarat'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/get', label: 'GET Sifarişi oxu'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/replace', label: 'PUT Sifarişi yenilə'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/update', label: 'PATCH Sifarişi yenilə'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/delete', label: 'DELETE Sifarişi sil'},
                {type: 'doc', id: 'api/modules/purchase/purchase-orders/change-state', label: 'PATCH Sifariş state-i'},
              ],
            },
            {
              type: 'category', label: 'Alış qəbzləri', collapsible: true, collapsed: true,
              items: [
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts', label: 'İcmal'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/list', label: 'GET Qəbzləri siyahıla'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/create', label: 'POST Qəbz yarat'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/get', label: 'GET Qəbzi oxu'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/replace', label: 'PUT Qəbzi yenilə'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/update', label: 'PATCH Qəbzi yenilə'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/delete', label: 'DELETE Qəbzi sil'},
                {type: 'doc', id: 'api/modules/purchase/purchase-receipts/change-state', label: 'PATCH Qəbz state-i'},
              ],
            },
          ],
        },
        'api/coverage',
      ],
    },
    {
      type: 'category',
      label: 'Arxitektura',
      items: ['architecture/overview', 'architecture/tenancy', 'architecture/business-documents'],
    },
    'modules/index',
    'contributing',
  ],
};
